project_id = "jk-mlops-dev"
region = "us-central1"
zone = "us-central1-a"
name_prefix = "jk-bert-lab"
machine_type = "a2-highgpu-2g"
container_image = "gcr.io/deeplearning-platform-release/tf2-cpu.2-3"
